### ISSUE TITLE
Some questions I had. 

### ISSUE THREAD

**Issue by jensenhuangyankai** [FadiniGIT/Razer-Blade-Stealth-Hackintosh-Guide#1]
Hey! First of all, great guide! 

I'm on a blade 14", and I've already hackintoshed it. However, I can't seem to get the battery indicator and the trackpad to work ( apart from the 1060, which is impossible to get working ). I've tried following the guides before but they don't seem to work for me. Is it possible for you to include some more specific details for the blade? They should be pretty similar, since mine has the same architecture (Kaby lake). 

Thanks!

**Comment by FadiniGIT** [comment]
@jensenhuangyankai 
Try to copy the DSDT files from /Laptop EFI Setup/EFI/CLOVER/ACPI/patched to same location on your EFI system partition. (This may change the Model Identifier of your machine)

For battery kexts, copy /Laptop System Drive/Library/Extensions/ACPIBatteryManager.kext to /L/E on your system and to your EFI partitions CLOVER/kexts/other (I have not tested which one is necessary, but having in both works for me)

For trackpad, hopefully the Blade 14 uses the I2C input controller for the trackpad, I had to edit the DSDT as well as add/remove kexts, add all the VoodooI2C kexts in /Laptop EFI Setup/EFI/CLOVER/kexts/other to /L/E and the EFI partition's other kexts directory. (same deal as above with not knowing which is necessary but having all work)

For the trackpad to work, delete the kexts AppleIntelLpssI2C.kext and AppleIntelLpssI2CController.kext From /System/Library/Extentions 


Hopefully this can help you out :)
-Fadini
