### ISSUE TITLE
Is this a dual boot guide?

### ISSUE THREAD

**Issue by zachthedev** [FadiniGIT/Razer-Blade-Stealth-Hackintosh-Guide#2]
Title says it all, but is it possible to follow this guide and run windows and OSX together? I want to keep using windows normally, but then boot into OSX for IOS development. Thanks!

**Comment by FadiniGIT** [comment]
its not a dual boot guide, but I ended up partitioning my drive in half and installing windows onto that, and then change the bios to boot to clover again after installation is all finished, and profit, then you choose windows in the clover menu
