### ISSUE TITLE
Trackpad instructions

### ISSUE THREAD

**Issue by anpato** [FadiniGIT/Razer-Blade-Stealth-Hackintosh-Guide#3]
I followed your guide to get the trackpad working, unfortunately it is still not working, do you have a specific way that you did it.

**Comment by FadiniGIT** [comment]
Did you install the VoodooI2C (the kexts in the S/L/E from the guide) and remove the system kexts in S/L/E that are listed to be removed

**Comment by anpato** [comment]
Yes, now what wasn't to clear was wether the kexts have to be force removed from the terminal or if they can be dragged into the trash.

**Comment by FadiniGIT** [comment]
Move to trash and empty it ¯\_(ツ)_/¯  

Maybe thatll help and try a few reboots...if not, go to the link for voodoo and try to install it yourself with the download from there and let me know how it goes
