### ISSUE TITLE
End Randomseed +

### ISSUE THREAD

**Issue by ShawnXXK** [FadiniGIT/Razer-Blade-Stealth-Hackintosh-Guide#5]
It seems that i met a problem.

1,Downloaded macOS Mojave 10.14 18A391 with Clover 4674.
2,etcher flash in my USB drive,Open the EFI partition from the flash drive - copy the files in USB DRIVE STUFF/USB EFI Partition/EFI/CLOVER/ to /EFI/CLOVER on the flash drive as you say.
3,After bios set well,I went to clover and boot the install Option.
4,End Randomseed + shows up.

Enviroment:win10 1803

Tried:replace drvers 64uefi/ApfsDriverLoader-64.efi and AptioMemoruFix-64.efi

**Comment by lholliger** [comment]
How was this issue fixed? My laptop still has this issue

**Comment by ShawnXXK** [comment]
> 这个问题是如何解决的？我的笔记本电脑仍有此问题

Inject Ram information

**Comment by lholliger** [comment]
Is there a guide to do this?
